name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm clean-install
      - name: Static analysis
        run: npm run lint
      - name: Check format files
        run: npm run prettier
      - name: Run unit tests
        run: npm run test
      - name: Build
        run: docker build -t hello-world .
